version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    package-name: "*" 
    target-branch: "fix/dependabot_alerts" 
    commit-message: "Bump dependencies" 

