FROM mcr.microsoft.com/playwright:v1.40.0-jammy
# TODO remove after update
RUN npm install -g n && n 20.19.0 && npm uninstall -g n

WORKDIR /app

VOLUME /app/test-results

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

CMD ["yarn", "screenshots"]