// flow-typed signature: e50f19f15f510206ec00e6bd28ae0049
// flow-typed version: <<STUB>>/color-hash_v1.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "color-hash" {
    declare type options = $Exact<{
      hash: (str: string) => number,
      lightness: number | Array<number>,
      saturation: number | Array<number>
    }>;

    declare class ColorHash {
      constructor(options: $Shape<options>): void;
      hsl(str: string): Array<number>;
      rgb(str: string): Array<number>;
      hex(str: string): string;
    }

    declare module.exports: Class<ColorHash>;
  }
