// flow-typed signature: 64399a259c339755f488249c6dcb8e57
// flow-typed version: <<STUB>>/storybook-react-router_v1.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

 type LocationShape = {
	pathname?: string,
	search?: string,
	hash?: string,
	state?: any
 };

 type GetUserConfirmation = (
	message: string,
	callback: (confirmed: boolean) => void
) => void;

declare module 'storybook-react-router' {
	declare type Context = { kind: string, story: string };
	declare type Renderable = React$Element<*>;
	declare type RenderFunction = () => Renderable | Array<Renderable>;

	declare type StoryDecorator = (
	  story: RenderFunction,
	  context: Context
	) => Renderable | null;

	declare type Links = {
	  [key: string]: (kind: string, story: string) => Function
	};

	declare type RouterProps = {
	  initialEntry?: Array<string>,
	  autoRoute?: boolean,
	  initialEntries?: Array<LocationShape | string>,
	  initialIndex?: number,
	  getUserConfirmation?: GetUserConfirmation,
	  keyLength?: number,
	  children?: React$Element<*>
	};

	declare module.exports: {
		(links?: Links, routerProps?: RouterProps): StoryDecorator
	};
}
