export const MAX_METRIC_LIST_LENGTH_BEFORE_SCROLLABLE = 25;
export const METRIC_LIST_HEIGHT = 500;
export const METRIC_LIST_ROW_HEIGHT = 20;
export const METRIC_LIST_ROW_PADDING = 5;

export const MAX_TAG_LIST_LENGTH_BEFORE_SCROLLABLE = 40;
export const TAG_LIST_HEIGHT = 1000;
export const TAG_ROW_HEIGHT = 25;

export const SUBSCRIPTION_LIST_HEIGHT = 500;
