// flow-typed signature: e81e8632b0349e9e85aa814e06ab1016
// flow-typed version: <<STUB>>/@skbkontur/react-icons_v3.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@skbkontur/react-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@skbkontur/react-icons' {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

declare type SvgProps = {
    color?: string;
    size?: string | number;
}

declare module '@skbkontur/react-icons/Add' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/AddColumnLeft' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/AddColumnRight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/AddRowBottom' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/AddRowTop' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Android' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Apple' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArchivePack' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArchiveUnpack' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowBoldDown' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowBoldLeft' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowBoldRight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowBoldUp' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowChevron2Left' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowChevron2Right' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowChevronDown' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowChevronLeft' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowChevronRight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowChevronUp' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowCorner1' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowDrag' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowParallelHorizontal' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowParallelVertical' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowSize1' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowSize2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowSize3' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowSize4' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowSizeMax' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowSizeMin' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleDown' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleLeft' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleRight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleUp' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleUpDown' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleUpDown2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleUpDown3' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ArrowTriangleUpDown4' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Attach' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Baby' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Backward' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BarcodeScanner' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Baseline' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderAll' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderBottom' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderInside' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderLeft' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderNone' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderOutside' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderRight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/BorderTop' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Briefcase' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Calculator' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Calendar' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Card' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/CellsEqualHeight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/CellsEqualWidth' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/CellsMerge' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/CellsSplit' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Certificate' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Clear' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Clock' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Cloud' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Coin' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Coins' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/CommentLite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/CommentLiteAdd' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/CommentSolid' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Copy' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Crown' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Delete' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DeleteColumn' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DeleteRow' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Delta' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DeviceSmartphone' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DeviceSmartphoneNo' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentAdd' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentCheck' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentCheck2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentConvert' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentCopy' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentFolder' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentGroup' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentLite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentRefresh' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentSolid' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentTypeCsv' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentTypeDoc' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentTypePdf' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentTypeRtf' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentTypeTxt' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentTypeXls' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DocumentTypeXml' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Dot12' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Dot12Dashed' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Dot12Lite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Dot8' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Dot8Lite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Dot8LiteOff' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Download' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/DragBorder' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Edit' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Ellipsis' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/EmoticonHappy' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/EmoticonSad' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Error' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Export' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/EyeClosed' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/EyeOpened' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Facebook' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Facebook2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Filter' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Fired' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/FlagLite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/FlagSolid' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/FontSize' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/FormatCopy' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Forward' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Function' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/GooglePlus' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/GooglePlus2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Grid' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Handshake' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Heart' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/HeartLite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/HelpBook' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/HelpDot' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/HelpLite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Home' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/HomeOffice' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Hyphen' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Import' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Infiniti' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Info' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Instagram' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Instagram2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/internal/icons' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/internal/SvgIcon' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Key' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Lightbulb' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Link' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/LinkOff' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ListGroup' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ListRows' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Loading' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/LockClosed' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/LockOpened' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Login' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Logout' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Mail' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Mail2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Mail2In' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Mail2Out' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/MapPin' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Marker' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Medical' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Menu' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/MenuDots' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/MenuKebab' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/NewWindow' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/NotificationBell' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/NotificationBellNone' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/NotificationBellOff' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/NotificationBellOn' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Odnoklassniki' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Odnoklassniki2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Ok' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/OkDouble' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/OwnershipBoat' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/OwnershipCar' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ParaToCells' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Pause' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/PC' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/People' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Phone' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Phone2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Pin' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Print' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Redo' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Refresh' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Remove' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Reply' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Rss' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Rss2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Ruble' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Search' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Send' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Send2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Send3' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Settings' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Shadelight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Shipment' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ShopCashregister' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ShoppingCartLite' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ShoppingCartSolid' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ShopReceipt' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Skip' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/SortDown' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/SortUp' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Space' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Star' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Star2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Statistic' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/StructureTree' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Sum' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/TableDelete' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/TableSplit' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Tag' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Telegram' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Telegram2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/TextAlignCenter' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/TextAlignLeft' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/TextAlignRight' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/TextNbsp' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/TextWidthFixed' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ThumbDown' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/ThumbUp' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Trash' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Twitter' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Twitter2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Underscore' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Undo' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Upload' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/USB' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/User' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/UserAdd' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/UserSettings' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Vacation' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Video' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Video2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Vkontakte' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Vkontakte2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Warning' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Windows' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Youtube' {
  declare module.exports: (props: SvgProps) => React$Node;
}

declare module '@skbkontur/react-icons/Youtube2' {
  declare module.exports: (props: SvgProps) => React$Node;
}

// Filename aliases
declare module '@skbkontur/react-icons/Add.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Add'>;
}
declare module '@skbkontur/react-icons/AddColumnLeft.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/AddColumnLeft'>;
}
declare module '@skbkontur/react-icons/AddColumnRight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/AddColumnRight'>;
}
declare module '@skbkontur/react-icons/AddRowBottom.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/AddRowBottom'>;
}
declare module '@skbkontur/react-icons/AddRowTop.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/AddRowTop'>;
}
declare module '@skbkontur/react-icons/Android.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Android'>;
}
declare module '@skbkontur/react-icons/Apple.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Apple'>;
}
declare module '@skbkontur/react-icons/ArchivePack.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArchivePack'>;
}
declare module '@skbkontur/react-icons/ArchiveUnpack.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArchiveUnpack'>;
}
declare module '@skbkontur/react-icons/ArrowBoldDown.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowBoldDown'>;
}
declare module '@skbkontur/react-icons/ArrowBoldLeft.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowBoldLeft'>;
}
declare module '@skbkontur/react-icons/ArrowBoldRight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowBoldRight'>;
}
declare module '@skbkontur/react-icons/ArrowBoldUp.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowBoldUp'>;
}
declare module '@skbkontur/react-icons/ArrowChevron2Left.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowChevron2Left'>;
}
declare module '@skbkontur/react-icons/ArrowChevron2Right.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowChevron2Right'>;
}
declare module '@skbkontur/react-icons/ArrowChevronDown.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowChevronDown'>;
}
declare module '@skbkontur/react-icons/ArrowChevronLeft.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowChevronLeft'>;
}
declare module '@skbkontur/react-icons/ArrowChevronRight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowChevronRight'>;
}
declare module '@skbkontur/react-icons/ArrowChevronUp.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowChevronUp'>;
}
declare module '@skbkontur/react-icons/ArrowCorner1.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowCorner1'>;
}
declare module '@skbkontur/react-icons/ArrowDrag.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowDrag'>;
}
declare module '@skbkontur/react-icons/ArrowParallelHorizontal.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowParallelHorizontal'>;
}
declare module '@skbkontur/react-icons/ArrowParallelVertical.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowParallelVertical'>;
}
declare module '@skbkontur/react-icons/ArrowSize1.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowSize1'>;
}
declare module '@skbkontur/react-icons/ArrowSize2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowSize2'>;
}
declare module '@skbkontur/react-icons/ArrowSize3.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowSize3'>;
}
declare module '@skbkontur/react-icons/ArrowSize4.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowSize4'>;
}
declare module '@skbkontur/react-icons/ArrowSizeMax.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowSizeMax'>;
}
declare module '@skbkontur/react-icons/ArrowSizeMin.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowSizeMin'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleDown.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleDown'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleLeft.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleLeft'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleRight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleRight'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleUp.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleUp'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleUpDown.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleUpDown'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleUpDown2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleUpDown2'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleUpDown3.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleUpDown3'>;
}
declare module '@skbkontur/react-icons/ArrowTriangleUpDown4.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ArrowTriangleUpDown4'>;
}
declare module '@skbkontur/react-icons/Attach.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Attach'>;
}
declare module '@skbkontur/react-icons/Baby.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Baby'>;
}
declare module '@skbkontur/react-icons/Backward.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Backward'>;
}
declare module '@skbkontur/react-icons/BarcodeScanner.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BarcodeScanner'>;
}
declare module '@skbkontur/react-icons/Baseline.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Baseline'>;
}
declare module '@skbkontur/react-icons/BorderAll.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderAll'>;
}
declare module '@skbkontur/react-icons/BorderBottom.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderBottom'>;
}
declare module '@skbkontur/react-icons/BorderInside.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderInside'>;
}
declare module '@skbkontur/react-icons/BorderLeft.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderLeft'>;
}
declare module '@skbkontur/react-icons/BorderNone.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderNone'>;
}
declare module '@skbkontur/react-icons/BorderOutside.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderOutside'>;
}
declare module '@skbkontur/react-icons/BorderRight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderRight'>;
}
declare module '@skbkontur/react-icons/BorderTop.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/BorderTop'>;
}
declare module '@skbkontur/react-icons/Briefcase.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Briefcase'>;
}
declare module '@skbkontur/react-icons/Calculator.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Calculator'>;
}
declare module '@skbkontur/react-icons/Calendar.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Calendar'>;
}
declare module '@skbkontur/react-icons/Card.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Card'>;
}
declare module '@skbkontur/react-icons/CellsEqualHeight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/CellsEqualHeight'>;
}
declare module '@skbkontur/react-icons/CellsEqualWidth.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/CellsEqualWidth'>;
}
declare module '@skbkontur/react-icons/CellsMerge.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/CellsMerge'>;
}
declare module '@skbkontur/react-icons/CellsSplit.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/CellsSplit'>;
}
declare module '@skbkontur/react-icons/Certificate.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Certificate'>;
}
declare module '@skbkontur/react-icons/Clear.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Clear'>;
}
declare module '@skbkontur/react-icons/Clock.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Clock'>;
}
declare module '@skbkontur/react-icons/Cloud.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Cloud'>;
}
declare module '@skbkontur/react-icons/Coin.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Coin'>;
}
declare module '@skbkontur/react-icons/Coins.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Coins'>;
}
declare module '@skbkontur/react-icons/CommentLite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/CommentLite'>;
}
declare module '@skbkontur/react-icons/CommentLiteAdd.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/CommentLiteAdd'>;
}
declare module '@skbkontur/react-icons/CommentSolid.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/CommentSolid'>;
}
declare module '@skbkontur/react-icons/Copy.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Copy'>;
}
declare module '@skbkontur/react-icons/Crown.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Crown'>;
}
declare module '@skbkontur/react-icons/Delete.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Delete'>;
}
declare module '@skbkontur/react-icons/DeleteColumn.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DeleteColumn'>;
}
declare module '@skbkontur/react-icons/DeleteRow.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DeleteRow'>;
}
declare module '@skbkontur/react-icons/Delta.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Delta'>;
}
declare module '@skbkontur/react-icons/DeviceSmartphone.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DeviceSmartphone'>;
}
declare module '@skbkontur/react-icons/DeviceSmartphoneNo.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DeviceSmartphoneNo'>;
}
declare module '@skbkontur/react-icons/DocumentAdd.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentAdd'>;
}
declare module '@skbkontur/react-icons/DocumentCheck.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentCheck'>;
}
declare module '@skbkontur/react-icons/DocumentCheck2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentCheck2'>;
}
declare module '@skbkontur/react-icons/DocumentConvert.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentConvert'>;
}
declare module '@skbkontur/react-icons/DocumentCopy.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentCopy'>;
}
declare module '@skbkontur/react-icons/DocumentFolder.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentFolder'>;
}
declare module '@skbkontur/react-icons/DocumentGroup.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentGroup'>;
}
declare module '@skbkontur/react-icons/DocumentLite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentLite'>;
}
declare module '@skbkontur/react-icons/DocumentRefresh.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentRefresh'>;
}
declare module '@skbkontur/react-icons/DocumentSolid.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentSolid'>;
}
declare module '@skbkontur/react-icons/DocumentTypeCsv.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentTypeCsv'>;
}
declare module '@skbkontur/react-icons/DocumentTypeDoc.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentTypeDoc'>;
}
declare module '@skbkontur/react-icons/DocumentTypePdf.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentTypePdf'>;
}
declare module '@skbkontur/react-icons/DocumentTypeRtf.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentTypeRtf'>;
}
declare module '@skbkontur/react-icons/DocumentTypeTxt.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentTypeTxt'>;
}
declare module '@skbkontur/react-icons/DocumentTypeXls.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentTypeXls'>;
}
declare module '@skbkontur/react-icons/DocumentTypeXml.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DocumentTypeXml'>;
}
declare module '@skbkontur/react-icons/Dot12.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Dot12'>;
}
declare module '@skbkontur/react-icons/Dot12Dashed.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Dot12Dashed'>;
}
declare module '@skbkontur/react-icons/Dot12Lite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Dot12Lite'>;
}
declare module '@skbkontur/react-icons/Dot8.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Dot8'>;
}
declare module '@skbkontur/react-icons/Dot8Lite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Dot8Lite'>;
}
declare module '@skbkontur/react-icons/Dot8LiteOff.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Dot8LiteOff'>;
}
declare module '@skbkontur/react-icons/Download.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Download'>;
}
declare module '@skbkontur/react-icons/DragBorder.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/DragBorder'>;
}
declare module '@skbkontur/react-icons/Edit.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Edit'>;
}
declare module '@skbkontur/react-icons/Ellipsis.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Ellipsis'>;
}
declare module '@skbkontur/react-icons/EmoticonHappy.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/EmoticonHappy'>;
}
declare module '@skbkontur/react-icons/EmoticonSad.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/EmoticonSad'>;
}
declare module '@skbkontur/react-icons/Error.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Error'>;
}
declare module '@skbkontur/react-icons/Export.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Export'>;
}
declare module '@skbkontur/react-icons/EyeClosed.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/EyeClosed'>;
}
declare module '@skbkontur/react-icons/EyeOpened.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/EyeOpened'>;
}
declare module '@skbkontur/react-icons/Facebook.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Facebook'>;
}
declare module '@skbkontur/react-icons/Facebook2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Facebook2'>;
}
declare module '@skbkontur/react-icons/Filter.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Filter'>;
}
declare module '@skbkontur/react-icons/Fired.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Fired'>;
}
declare module '@skbkontur/react-icons/FlagLite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/FlagLite'>;
}
declare module '@skbkontur/react-icons/FlagSolid.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/FlagSolid'>;
}
declare module '@skbkontur/react-icons/FontSize.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/FontSize'>;
}
declare module '@skbkontur/react-icons/FormatCopy.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/FormatCopy'>;
}
declare module '@skbkontur/react-icons/Forward.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Forward'>;
}
declare module '@skbkontur/react-icons/Function.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Function'>;
}
declare module '@skbkontur/react-icons/GooglePlus.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/GooglePlus'>;
}
declare module '@skbkontur/react-icons/GooglePlus2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/GooglePlus2'>;
}
declare module '@skbkontur/react-icons/Grid.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Grid'>;
}
declare module '@skbkontur/react-icons/Handshake.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Handshake'>;
}
declare module '@skbkontur/react-icons/Heart.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Heart'>;
}
declare module '@skbkontur/react-icons/HeartLite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/HeartLite'>;
}
declare module '@skbkontur/react-icons/HelpBook.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/HelpBook'>;
}
declare module '@skbkontur/react-icons/HelpDot.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/HelpDot'>;
}
declare module '@skbkontur/react-icons/HelpLite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/HelpLite'>;
}
declare module '@skbkontur/react-icons/Home.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Home'>;
}
declare module '@skbkontur/react-icons/HomeOffice.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/HomeOffice'>;
}
declare module '@skbkontur/react-icons/Hyphen.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Hyphen'>;
}
declare module '@skbkontur/react-icons/Import.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Import'>;
}
declare module '@skbkontur/react-icons/index' {
  declare module.exports: $Exports<'@skbkontur/react-icons'>;
}
declare module '@skbkontur/react-icons/index.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons'>;
}
declare module '@skbkontur/react-icons/Infiniti.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Infiniti'>;
}
declare module '@skbkontur/react-icons/Info.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Info'>;
}
declare module '@skbkontur/react-icons/Instagram.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Instagram'>;
}
declare module '@skbkontur/react-icons/Instagram2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Instagram2'>;
}
declare module '@skbkontur/react-icons/internal/icons.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/internal/icons'>;
}
declare module '@skbkontur/react-icons/internal/SvgIcon.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/internal/SvgIcon'>;
}
declare module '@skbkontur/react-icons/Key.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Key'>;
}
declare module '@skbkontur/react-icons/Lightbulb.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Lightbulb'>;
}
declare module '@skbkontur/react-icons/Link.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Link'>;
}
declare module '@skbkontur/react-icons/LinkOff.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/LinkOff'>;
}
declare module '@skbkontur/react-icons/ListGroup.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ListGroup'>;
}
declare module '@skbkontur/react-icons/ListRows.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ListRows'>;
}
declare module '@skbkontur/react-icons/Loading.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Loading'>;
}
declare module '@skbkontur/react-icons/LockClosed.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/LockClosed'>;
}
declare module '@skbkontur/react-icons/LockOpened.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/LockOpened'>;
}
declare module '@skbkontur/react-icons/Login.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Login'>;
}
declare module '@skbkontur/react-icons/Logout.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Logout'>;
}
declare module '@skbkontur/react-icons/Mail.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Mail'>;
}
declare module '@skbkontur/react-icons/Mail2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Mail2'>;
}
declare module '@skbkontur/react-icons/Mail2In.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Mail2In'>;
}
declare module '@skbkontur/react-icons/Mail2Out.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Mail2Out'>;
}
declare module '@skbkontur/react-icons/MapPin.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/MapPin'>;
}
declare module '@skbkontur/react-icons/Marker.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Marker'>;
}
declare module '@skbkontur/react-icons/Medical.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Medical'>;
}
declare module '@skbkontur/react-icons/Menu.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Menu'>;
}
declare module '@skbkontur/react-icons/MenuDots.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/MenuDots'>;
}
declare module '@skbkontur/react-icons/MenuKebab.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/MenuKebab'>;
}
declare module '@skbkontur/react-icons/NewWindow.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/NewWindow'>;
}
declare module '@skbkontur/react-icons/NotificationBell.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/NotificationBell'>;
}
declare module '@skbkontur/react-icons/NotificationBellNone.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/NotificationBellNone'>;
}
declare module '@skbkontur/react-icons/NotificationBellOff.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/NotificationBellOff'>;
}
declare module '@skbkontur/react-icons/NotificationBellOn.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/NotificationBellOn'>;
}
declare module '@skbkontur/react-icons/Odnoklassniki.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Odnoklassniki'>;
}
declare module '@skbkontur/react-icons/Odnoklassniki2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Odnoklassniki2'>;
}
declare module '@skbkontur/react-icons/Ok.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Ok'>;
}
declare module '@skbkontur/react-icons/OkDouble.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/OkDouble'>;
}
declare module '@skbkontur/react-icons/OwnershipBoat.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/OwnershipBoat'>;
}
declare module '@skbkontur/react-icons/OwnershipCar.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/OwnershipCar'>;
}
declare module '@skbkontur/react-icons/ParaToCells.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ParaToCells'>;
}
declare module '@skbkontur/react-icons/Pause.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Pause'>;
}
declare module '@skbkontur/react-icons/PC.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/PC'>;
}
declare module '@skbkontur/react-icons/People.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/People'>;
}
declare module '@skbkontur/react-icons/Phone.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Phone'>;
}
declare module '@skbkontur/react-icons/Phone2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Phone2'>;
}
declare module '@skbkontur/react-icons/Pin.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Pin'>;
}
declare module '@skbkontur/react-icons/Print.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Print'>;
}
declare module '@skbkontur/react-icons/Redo.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Redo'>;
}
declare module '@skbkontur/react-icons/Refresh.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Refresh'>;
}
declare module '@skbkontur/react-icons/Remove.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Remove'>;
}
declare module '@skbkontur/react-icons/Reply.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Reply'>;
}
declare module '@skbkontur/react-icons/Rss.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Rss'>;
}
declare module '@skbkontur/react-icons/Rss2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Rss2'>;
}
declare module '@skbkontur/react-icons/Ruble.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Ruble'>;
}
declare module '@skbkontur/react-icons/Search.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Search'>;
}
declare module '@skbkontur/react-icons/Send.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Send'>;
}
declare module '@skbkontur/react-icons/Send2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Send2'>;
}
declare module '@skbkontur/react-icons/Send3.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Send3'>;
}
declare module '@skbkontur/react-icons/Settings.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Settings'>;
}
declare module '@skbkontur/react-icons/Shadelight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Shadelight'>;
}
declare module '@skbkontur/react-icons/Shipment.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Shipment'>;
}
declare module '@skbkontur/react-icons/ShopCashregister.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ShopCashregister'>;
}
declare module '@skbkontur/react-icons/ShoppingCartLite.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ShoppingCartLite'>;
}
declare module '@skbkontur/react-icons/ShoppingCartSolid.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ShoppingCartSolid'>;
}
declare module '@skbkontur/react-icons/ShopReceipt.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ShopReceipt'>;
}
declare module '@skbkontur/react-icons/Skip.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Skip'>;
}
declare module '@skbkontur/react-icons/SortDown.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/SortDown'>;
}
declare module '@skbkontur/react-icons/SortUp.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/SortUp'>;
}
declare module '@skbkontur/react-icons/Space.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Space'>;
}
declare module '@skbkontur/react-icons/Star.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Star'>;
}
declare module '@skbkontur/react-icons/Star2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Star2'>;
}
declare module '@skbkontur/react-icons/Statistic.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Statistic'>;
}
declare module '@skbkontur/react-icons/StructureTree.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/StructureTree'>;
}
declare module '@skbkontur/react-icons/Sum.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Sum'>;
}
declare module '@skbkontur/react-icons/TableDelete.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/TableDelete'>;
}
declare module '@skbkontur/react-icons/TableSplit.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/TableSplit'>;
}
declare module '@skbkontur/react-icons/Tag.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Tag'>;
}
declare module '@skbkontur/react-icons/Telegram.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Telegram'>;
}
declare module '@skbkontur/react-icons/Telegram2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Telegram2'>;
}
declare module '@skbkontur/react-icons/TextAlignCenter.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/TextAlignCenter'>;
}
declare module '@skbkontur/react-icons/TextAlignLeft.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/TextAlignLeft'>;
}
declare module '@skbkontur/react-icons/TextAlignRight.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/TextAlignRight'>;
}
declare module '@skbkontur/react-icons/TextNbsp.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/TextNbsp'>;
}
declare module '@skbkontur/react-icons/TextWidthFixed.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/TextWidthFixed'>;
}
declare module '@skbkontur/react-icons/ThumbDown.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ThumbDown'>;
}
declare module '@skbkontur/react-icons/ThumbUp.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/ThumbUp'>;
}
declare module '@skbkontur/react-icons/Trash.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Trash'>;
}
declare module '@skbkontur/react-icons/Twitter.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Twitter'>;
}
declare module '@skbkontur/react-icons/Twitter2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Twitter2'>;
}
declare module '@skbkontur/react-icons/Underscore.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Underscore'>;
}
declare module '@skbkontur/react-icons/Undo.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Undo'>;
}
declare module '@skbkontur/react-icons/Upload.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Upload'>;
}
declare module '@skbkontur/react-icons/USB.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/USB'>;
}
declare module '@skbkontur/react-icons/User.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/User'>;
}
declare module '@skbkontur/react-icons/UserAdd.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/UserAdd'>;
}
declare module '@skbkontur/react-icons/UserSettings.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/UserSettings'>;
}
declare module '@skbkontur/react-icons/Vacation.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Vacation'>;
}
declare module '@skbkontur/react-icons/Video.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Video'>;
}
declare module '@skbkontur/react-icons/Video2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Video2'>;
}
declare module '@skbkontur/react-icons/Vkontakte.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Vkontakte'>;
}
declare module '@skbkontur/react-icons/Vkontakte2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Vkontakte2'>;
}
declare module '@skbkontur/react-icons/Warning.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Warning'>;
}
declare module '@skbkontur/react-icons/Windows.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Windows'>;
}
declare module '@skbkontur/react-icons/Youtube.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Youtube'>;
}
declare module '@skbkontur/react-icons/Youtube2.js' {
  declare module.exports: $Exports<'@skbkontur/react-icons/Youtube2'>;
}
