// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lOVQPOOObQPO'#CbO!PQPO'#CaOOQO'#Cg'#CgQVQPOOO!UQPO'#CiO!ZQPO,59OOOQO,59Q,59QO!rQPO,58{OOQO-E6e-E6eOOQO,59T,59TOOQO-E6g-E6gOOQO1G.g1G.gO#QQPO1G.gO#VQPO'#CnOOQO7+$R7+$RO#hQPO,59YOVQPO'#ChOOQO-E6f-E6fO#pQPO,59S",
  stateData: "$R~O`OS~OQRORROaPO~OXVOdTOQWXRWXVUX^WXaWXSWXcWX~OVWO~OaYO~OdTOQWaRWa^WaaWaSWacWa~OQRORROS[OaPO~OS_O~OQRORROaPOcaOSbX~OcaOSba~OQRORROaPOS[ac[a~O",
  goto: "!ccPPPPPdlPdPdt!S!YPPPP!`]ROSW^ac]QOSW^acQSOUXS^cQ^WRcaQ`^Rb`QUPRZUR]W",
  nodeNames: "⚠ BuiltExpression String Number ) FunctionCall FunctionName ( Value = Variable",
  maxTerm: 20,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "%a~RdX^!apq!ars#Uwx#sxy$]yz$b|}$g!O!P$l!Q![$q!_!`$y!c!}%O#T#o%O#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~!fY`~X^!apq!a#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~#XTOr#Urs#hs;'S#U;'S;=`#m<%lO#U~#mOQ~~#pP;=`<%l#U~#vTOw#swx#hx;'S#s;'S;=`$V<%lO#s~$YP;=`<%l#s~$bOV~~$gOS~~$lOc~~$qOd~~$vPR~!Q![$q~%OOX~~%TSa~!Q![%O!c!}%O#R#S%O#T#o%O",
  tokenizers: [0],
  topRules: {"BuiltExpression":[0,1]},
  tokenPrec: 0
})
