// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fOVQPOOObQPO'#CbO|QPO'#CaOOQO'#Ce'#CeQVQPOOO!RQPO'#CgO!WQPO,59OO!oQPO,58{OOQO-E6c-E6cOOQO,59R,59ROOQO-E6e-E6eOOQO1G.g1G.gO!}QPO1G.gO#SQPO'#ClOOQO7+$R7+$RO#eQPO,59WOVQPO'#CfOOQO-E6d-E6dO#mQPO,59Q",
  stateData: "$O~O^OS~OQRORRO_PO~ObTOQWXRWXVUX[WX_WXSWXaWX~OVVO~O_XO~ObTOQWaRWa[Wa_WaSWaaWa~OQRORROSZO_PO~OS^O~OQRORRO_POa`OS`X~Oa`OS`a~OQRORRO_POSYaaYa~O",
  goto: "!aaPPPPPbjPbr!Q!WPPPP!^]ROSV]`b]QOSV]`bQSOUWS]bQ]VRb`Q_]Ra_QUPRYUR[V",
  nodeNames: "⚠ BuiltExpression String Number ) FunctionCall FunctionName ( Variable",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "%X~RcX^!^pq!^rs#Rwx#pxy$Yyz$_|}$d!O!P$i!Q![$n!c!}$v#T#o$v#y#z!^$f$g!^#BY#BZ!^$IS$I_!^$I|$JO!^$JT$JU!^$KV$KW!^&FU&FV!^~!cY^~X^!^pq!^#y#z!^$f$g!^#BY#BZ!^$IS$I_!^$I|$JO!^$JT$JU!^$KV$KW!^&FU&FV!^~#UTOr#Rrs#es;'S#R;'S;=`#j<%lO#R~#jOQ~~#mP;=`<%l#R~#sTOw#pwx#ex;'S#p;'S;=`$S<%lO#p~$VP;=`<%l#p~$_OV~~$dOS~~$iOa~~$nOb~~$sPR~!Q![$n~${S_~!Q![$v!c!}$v#R#S$v#T#o$v",
  tokenizers: [0],
  topRules: {"BuiltExpression":[0,1]},
  tokenPrec: 0
})
