name: Publish docker release
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker tag
        run: echo "DOCKER_TAG=$(echo ${{github.ref_name}} | cut -c2-)}" >> $GITHUB_ENV
  
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          build-args: |
            MoiraVersion=${{env.DOCKER_TAG}}
            GIT_COMMIT=${{github.sha}}
          push: true
          tags: moira/web2.0:${{env.DOCKER_TAG}},moira/web2.0:latest
