name: E2E tests
on:
  pull_request:
jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: "yarn"
          
      - name: Install dependencies
        run: yarn install
          
      - name: Install Playwright
        run: npx playwright install --with-deps
          
      - name: Run tests
        run: npx playwright test
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: playwright-report
          path: playwright-report