name: Lint
on:
  pull_request:
jobs:
  lint:
    name: Lint the project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: make lint
