name: Publish packages
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build packages
        run: sudo apt-get update && sudo apt-get install ruby-dev build-essential && sudo gem i fpm -f && make packages


      - name: Release
        uses: docker://antonyurchenko/git-release:v4.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
        with:
          args: |
            build/moira*.tar.gz build/moira*.rpm build/moira*.deb
