name: Publish packages
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install fpm
        run: gem install fpm

      - name: Build packages
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: make packages

      - name: Release
        uses: docker://antonyurchenko/git-release:v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
        with:
          args: |
            build/moira*.tar.gz build/moira*.rpm build/moira*.deb
